---
# This file handles installation with yum (to default folder /opt/talend)
#
- name: "Install {{ app_name }} with yum"
  yum:
    name: "{{ rpm_name }}"
    state: present
  environment:
    TALEND_INSTALL_USER: '{{ install_user }}'
    TALEND_INSTALL_GROUP: '{{ install_group }}'
    TALEND_MWFL_PORT:    '{{ mwfl_port }}'
    JAVA_HOME:              "{{ java_dir.stdout }}"
